services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 5432:5432
    depends_on:
      - pg
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "rcdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
