services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3001:3001
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "3001"
    depends_on:
      - pg
      - s3
    environment:
      DATABASE_URL: "postgres://postgres:postgres@pg:5432/rcdb"
      SERVICE_URL: "0.0.0.0:3001"
      JWT_SECRET: "hehehehaw"

  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "rcdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./.local/dbdata:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "MINIO_ACCESS"
      MINIO_SECRET_KEY: "MINIO_SECRET"
    command: server /data
    volumes:
      - ./.local/s3data:/data
