services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - pg
    environment:
      DATABASE_URL: "postgres://postgres:postgres@pg:5432/rcdb"
      SERVICE_URL: "0.0.0.0:3001"
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "rcdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
